default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: spinel_development
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASS", "") %>

test:
  adapter: sqlite3
  database: ":memory:"
  pool: 5
  timeout: 5000

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
