source "https://rubygems.org"

ruby ">= 3.2.0"

gem "rails", "~> 8.0.0"
gem "pg", "~> 1.5"
gem "puma", ">= 6.0"
gem "bootsnap", require: false
gem "jwt", "~> 2.8"
gem "bcrypt", "~> 3.1.7"
gem "rack-cors"

group :development, :test do
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "database_cleaner-active_record"
end

group :test do
  gem "sqlite3"
end
